services:
  - type: web
    name: pothole-tagging-system
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free